### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by brucewar** [cnpm/nodeinstall#10]
![image](https://cloud.githubusercontent.com/assets/4013475/25980824/c8800c46-3703-11e7-9442-eed3a8a403ef.png)

Solution: Stop the process when timeout.

**Comment by popomore** [comment]
You can use --china flag
Bruce Wang <notifications@github.com>于2017年5月12日 周五11:13写道：

**Comment by brucewar** [comment]
sometimes timeout with --china!

**Comment by popomore** [comment]
I don't know why it's slow. If you are in China, `--china` will use mirror which is faster in china. Can you show me the error?

**Comment by unliar** [comment]
same problem. my network is fine . 

```
[nodeinstall] downloading [] 100% 0.0s/3.5s 18038506/18038506 4.61MB/s
ConnectionTimeoutError: Connect timeout for 5000ms, GET http://alinode.aliyun.com/dist/new-alinode/v3.11.8/SHASUMS256.txt -2 (connected: false, keepalive socket: false, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
    at Timeout._onTimeout (/app/node_modules/urllib/lib/urllib.js:849:15)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
The command '/bin/sh -c /app/node_modules/.bin/nodeinstall --install-alinode  v3.11.8' returned a non-zero code: 1
```
