### ISSUE TITLE
下载node 404

### ISSUE THREAD

**Issue by zuoye520** [cnpm/nodeinstall#13]
E:\GitPro\wanheng_pro>nodeinstall 7.6.0
Error: GET https://nodejs.org/dist/v7.6.0/node-v7.6.0-win-x86.tar.gz got 404
    at downloadTgz (C:\Users\Administrator.USER-20161009NP\AppData\Roaming\npm\node_modules\.nodeinstall_npminstall\node_modules\.0.1.3@nodeinstall\lib\installer\installer.js:125:17)
    at next (native)
    at onFulfilled (C:\Users\Administrator.USER-20161009NP\AppData\Roaming\npm\node_modules\.nodeinstall_npminstall\node_modules\.4.6.0@co\index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by fengmk2** [comment]
@popomore 应该是bug，windows 是 zip 才对 https://nodejs.org/dist/v7.6.0/node-v7.6.0-win-x86.zip

**Comment by popomore** [comment]
Windows 还不支持

**Comment by a526672351** [comment]
Windows  还有计划支持吗？
